name: peerpal
description: The PeerPAL Project


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flow_builder: ^0.0.2
  flutter_bloc: ^7.0.1
  equatable: ^2.0.2
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  meta: ^1.3.0
  formz: ^0.4.0
  cloud_firestore: ^2.2.2
  firebase_storage: ^8.1.3
  email_validator: ^2.0.1
  very_good_analysis: ^2.1.0
  zxcvbn: ^1.0.0
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

